name       : bluez-qt
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/bluez-qt-5.32.0.tar.xz : d0bf3ddc2ef4071137e9f25127a02ed2a4860fcf65cc68403b70ca97c165865e
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
rundeps    :
    - bluez
setup      : |
    # Adjust udev rules locations
    sed -i 's:/lib:/usr/lib64:' CMakeLists.txt
    %cmake .
build      : |
    %make
install    : |
    %make_install
