name       : bluez-qt
version    : 5.93.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/bluez-qt-5.93.0.tar.xz : ab5d84eaa37791b57c8379282a3c3afd7ef0b2ebbef83c3f12f6b3bfd9123624
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(bluez)
    - extra-cmake-modules
rundeps    :
    - bluez
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    # Adjust udev rules locations
    %patch -p1 -i $pkgfiles/0001-Adjust-udev-rules-locations.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
