name       : bluez-qt
version    : 5.46.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/bluez-qt-5.46.0.tar.xz : d4acf8bd6a7a6f0297300b7f80404c4cda508946f3c1ee4abe5bacd0fbedf841
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
rundeps    :
    - bluez
setup      : |
    # Adjust udev rules locations
    sed -i 's:/lib:/usr/lib64:' CMakeLists.txt
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
