name       : bluez-qt
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/bluez-qt-5.35.0.tar.xz : 0f3142f59d3ec9e7e5843034401ee4fc7f091efb46f410e6ed20ac96320443b4
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
rundeps    :
    - bluez
setup      : |
    # Adjust udev rules locations
    sed -i 's:/lib:/usr/lib64:' CMakeLists.txt
    %cmake .
build      : |
    %make
install    : |
    %make_install
