name       : bluez-qt
version    : 5.44.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/bluez-qt-5.44.0.tar.xz : bb73134db489fab1adde6e6f26a4298b07a36dfb3edba1671c01f3c3e0809f14
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
rundeps    :
    - bluez
setup      : |
    # Adjust udev rules locations
    sed -i 's:/lib:/usr/lib64:' CMakeLists.txt
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
