name       : bluez-qt
version    : 5.48.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/bluez-qt-5.48.0.tar.xz : 8924ef63a7fba7e2116139cd39c12d380f3d312ae2b341d9f160d26b5fe93791
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
rundeps    :
    - bluez
setup      : |
    # Adjust udev rules locations
    sed -i 's:/lib:/usr/lib64:' CMakeLists.txt
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
