name       : bluez-qt
version    : 5.72.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/bluez-qt-5.72.0.tar.xz : 4a69cf0350714453d904fba3ce7106b1c7f7f3a73784dfe4a08c5371f7b43229
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
rundeps    :
    - bluez
setup      : |
    # Adjust udev rules locations
    sed -i 's:/lib:/usr/lib64:' CMakeLists.txt
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
