name       : bluez-qt
version    : 5.94.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/bluez-qt-5.94.0.tar.xz : 7e776feb095e727abea0fec4b3ae3c81d704a0527b8ff3257d799feee2cc0632
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(bluez)
    - extra-cmake-modules
rundeps    :
    - bluez
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    # Adjust udev rules locations
    %patch -p1 -i $pkgfiles/0001-Adjust-udev-rules-locations.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
