name       : bluez-qt
version    : 5.82.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/bluez-qt-5.82.0.tar.xz : 1e8e52216219b48c0f07a322e78ee33a67ce0faf6f5cf6bbf205bf2b5b66f168
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(bluez)
    - extra-cmake-modules
rundeps    :
    - bluez
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    # Adjust udev rules locations
    %patch -p1 -i $pkgfiles/0001-Adjust-udev-rules-locations.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
