name       : bluez-qt
version    : 5.47.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/bluez-qt-5.47.0.tar.xz : 33acf34814ace5d412e3704e2de07ff52d6525021defd719daaff694dfdd0fdf
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for BlueZ 5 DBus API
description: |
    BluezQt is a library for communication with BlueZ system and session daemons.
    * Manager class is used to communicate with system daemon - org.bluez
    * ObexManager class is used to communicate with session daemon - org.bluez.obex
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
rundeps    :
    - bluez
setup      : |
    # Adjust udev rules locations
    sed -i 's:/lib:/usr/lib64:' CMakeLists.txt
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
